apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15.7
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "xtrace"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: xtrace-db-credentials
              key: DB_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: xtrace-db-credentials
              key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
